/* Generated by scripts/make-photos.py — do not edit by hand.
 *
 * Each entry is the normalised bounding box of the damage actually drawn
 * in that image, so the fake detector points at something real.
 */

export interface PhotoBox {
  x: number
  y: number
  w: number
  h: number
}

export const PHOTO_BOXES: PhotoBox[] = [
  {
    x: 0.2744,
    y: 0.4651,
    w: 0.2439,
    h: 0.2344
  },
  {
    x: 0.4128,
    y: 0.3027,
    w: 0.2735,
    h: 0.2713
  },
  {
    x: 0.3283,
    y: 0.3025,
    w: 0.2757,
    h: 0.242
  },
  {
    x: 0.424,
    y: 0.332,
    w: 0.2948,
    h: 0.288
  },
  {
    x: 0.2847,
    y: 0.4331,
    w: 0.3983,
    h: 0.3079
  },
  {
    x: 0.5013,
    y: 0.4234,
    w: 0.2588,
    h: 0.2522
  },
  {
    x: 0.2778,
    y: 0.4695,
    w: 0.2407,
    h: 0.244
  },
  {
    x: 0.3095,
    y: 0.5019,
    w: 0.2479,
    h: 0.2271
  }
]
